apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - live.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type : LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - protocol : TCP
      port: 5000
      targetPort: 5000