apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-l
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type : LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol : TCP
      port: 5050
      targetPort: 5050