apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - live.sh
          initialDelaySeconds: 30
          periodSeconds: 30
        ports:
        - containerPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type : LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol : TCP
      port: 5050
      targetPort: 5050